post http://localhost:8080/locations
content-type: application/json

{
    "building": "123 Main St",
    "room": "Room# 45",
    "shelf": "#6",
    "rack": "top"
}

###
post http://localhost:8080/locations
content-type: application/json

{
    "building": "123 45th Ave",
    "room": "Room# 678",
    "shelf": "#9",
    "rack": "bottom"    
}

###
get http://localhost:8080/locations


###
get http://localhost:8080/locations/460cdbb4-0706-4281-ab2f-9082b493cf80